#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AndroidSample.Resource", IsApplication=true)]

namespace AndroidSample
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Colours.Android.Resource.Color.almondColor = global::AndroidSample.Resource.Color.almondColor;
			global::Colours.Android.Resource.Color.antiqueWhiteColor = global::AndroidSample.Resource.Color.antiqueWhiteColor;
			global::Colours.Android.Resource.Color.babyBlueColor = global::AndroidSample.Resource.Color.babyBlueColor;
			global::Colours.Android.Resource.Color.background_dark = global::AndroidSample.Resource.Color.background_dark;
			global::Colours.Android.Resource.Color.background_holo_dark = global::AndroidSample.Resource.Color.background_holo_dark;
			global::Colours.Android.Resource.Color.background_holo_light = global::AndroidSample.Resource.Color.background_holo_light;
			global::Colours.Android.Resource.Color.background_light = global::AndroidSample.Resource.Color.background_light;
			global::Colours.Android.Resource.Color.bananaColor = global::AndroidSample.Resource.Color.bananaColor;
			global::Colours.Android.Resource.Color.beigeColor = global::AndroidSample.Resource.Color.beigeColor;
			global::Colours.Android.Resource.Color.black = global::AndroidSample.Resource.Color.black;
			global::Colours.Android.Resource.Color.black25PercentColor = global::AndroidSample.Resource.Color.black25PercentColor;
			global::Colours.Android.Resource.Color.black50PercentColor = global::AndroidSample.Resource.Color.black50PercentColor;
			global::Colours.Android.Resource.Color.black75PercentColor = global::AndroidSample.Resource.Color.black75PercentColor;
			global::Colours.Android.Resource.Color.blueberryColor = global::AndroidSample.Resource.Color.blueberryColor;
			global::Colours.Android.Resource.Color.brickRedColor = global::AndroidSample.Resource.Color.brickRedColor;
			global::Colours.Android.Resource.Color.bright_foreground_dark = global::AndroidSample.Resource.Color.bright_foreground_dark;
			global::Colours.Android.Resource.Color.bright_foreground_dark_disabled = global::AndroidSample.Resource.Color.bright_foreground_dark_disabled;
			global::Colours.Android.Resource.Color.bright_foreground_disabled_holo_dark = global::AndroidSample.Resource.Color.bright_foreground_disabled_holo_dark;
			global::Colours.Android.Resource.Color.bright_foreground_disabled_holo_light = global::AndroidSample.Resource.Color.bright_foreground_disabled_holo_light;
			global::Colours.Android.Resource.Color.bright_foreground_holo_dark = global::AndroidSample.Resource.Color.bright_foreground_holo_dark;
			global::Colours.Android.Resource.Color.bright_foreground_holo_light = global::AndroidSample.Resource.Color.bright_foreground_holo_light;
			global::Colours.Android.Resource.Color.bright_foreground_light = global::AndroidSample.Resource.Color.bright_foreground_light;
			global::Colours.Android.Resource.Color.burntOrangeColor = global::AndroidSample.Resource.Color.burntOrangeColor;
			global::Colours.Android.Resource.Color.burntSiennaColor = global::AndroidSample.Resource.Color.burntSiennaColor;
			global::Colours.Android.Resource.Color.buttermilkColor = global::AndroidSample.Resource.Color.buttermilkColor;
			global::Colours.Android.Resource.Color.cactusGreenColor = global::AndroidSample.Resource.Color.cactusGreenColor;
			global::Colours.Android.Resource.Color.cantaloupeColor = global::AndroidSample.Resource.Color.cantaloupeColor;
			global::Colours.Android.Resource.Color.cardTableColor = global::AndroidSample.Resource.Color.cardTableColor;
			global::Colours.Android.Resource.Color.carrotColor = global::AndroidSample.Resource.Color.carrotColor;
			global::Colours.Android.Resource.Color.charcoalColor = global::AndroidSample.Resource.Color.charcoalColor;
			global::Colours.Android.Resource.Color.chartreuseColor = global::AndroidSample.Resource.Color.chartreuseColor;
			global::Colours.Android.Resource.Color.chiliPowderColor = global::AndroidSample.Resource.Color.chiliPowderColor;
			global::Colours.Android.Resource.Color.chocolateColor = global::AndroidSample.Resource.Color.chocolateColor;
			global::Colours.Android.Resource.Color.cinnamonColor = global::AndroidSample.Resource.Color.cinnamonColor;
			global::Colours.Android.Resource.Color.coffeeColor = global::AndroidSample.Resource.Color.coffeeColor;
			global::Colours.Android.Resource.Color.coolGrayColor = global::AndroidSample.Resource.Color.coolGrayColor;
			global::Colours.Android.Resource.Color.coolPurpleColor = global::AndroidSample.Resource.Color.coolPurpleColor;
			global::Colours.Android.Resource.Color.coralColor = global::AndroidSample.Resource.Color.coralColor;
			global::Colours.Android.Resource.Color.cornflowerColor = global::AndroidSample.Resource.Color.cornflowerColor;
			global::Colours.Android.Resource.Color.creamColor = global::AndroidSample.Resource.Color.creamColor;
			global::Colours.Android.Resource.Color.crimsonColor = global::AndroidSample.Resource.Color.crimsonColor;
			global::Colours.Android.Resource.Color.dangerColor = global::AndroidSample.Resource.Color.dangerColor;
			global::Colours.Android.Resource.Color.denimColor = global::AndroidSample.Resource.Color.denimColor;
			global::Colours.Android.Resource.Color.dim_foreground_disabled_holo_dark = global::AndroidSample.Resource.Color.dim_foreground_disabled_holo_dark;
			global::Colours.Android.Resource.Color.dim_foreground_disabled_holo_light = global::AndroidSample.Resource.Color.dim_foreground_disabled_holo_light;
			global::Colours.Android.Resource.Color.dim_foreground_holo_dark = global::AndroidSample.Resource.Color.dim_foreground_holo_dark;
			global::Colours.Android.Resource.Color.dim_foreground_holo_light = global::AndroidSample.Resource.Color.dim_foreground_holo_light;
			global::Colours.Android.Resource.Color.dustColor = global::AndroidSample.Resource.Color.dustColor;
			global::Colours.Android.Resource.Color.easterPinkColor = global::AndroidSample.Resource.Color.easterPinkColor;
			global::Colours.Android.Resource.Color.eggplantColor = global::AndroidSample.Resource.Color.eggplantColor;
			global::Colours.Android.Resource.Color.eggshellColor = global::AndroidSample.Resource.Color.eggshellColor;
			global::Colours.Android.Resource.Color.emeraldColor = global::AndroidSample.Resource.Color.emeraldColor;
			global::Colours.Android.Resource.Color.fadedBlueColor = global::AndroidSample.Resource.Color.fadedBlueColor;
			global::Colours.Android.Resource.Color.fuschiaColor = global::AndroidSample.Resource.Color.fuschiaColor;
			global::Colours.Android.Resource.Color.ghostWhiteColor = global::AndroidSample.Resource.Color.ghostWhiteColor;
			global::Colours.Android.Resource.Color.goldColor = global::AndroidSample.Resource.Color.goldColor;
			global::Colours.Android.Resource.Color.goldenrodColor = global::AndroidSample.Resource.Color.goldenrodColor;
			global::Colours.Android.Resource.Color.grapeColor = global::AndroidSample.Resource.Color.grapeColor;
			global::Colours.Android.Resource.Color.grapefruitColor = global::AndroidSample.Resource.Color.grapefruitColor;
			global::Colours.Android.Resource.Color.grassColor = global::AndroidSample.Resource.Color.grassColor;
			global::Colours.Android.Resource.Color.highlighted_text_holo_dark = global::AndroidSample.Resource.Color.highlighted_text_holo_dark;
			global::Colours.Android.Resource.Color.highlighted_text_holo_light = global::AndroidSample.Resource.Color.highlighted_text_holo_light;
			global::Colours.Android.Resource.Color.hint_foreground_holo_dark = global::AndroidSample.Resource.Color.hint_foreground_holo_dark;
			global::Colours.Android.Resource.Color.hint_foreground_holo_light = global::AndroidSample.Resource.Color.hint_foreground_holo_light;
			global::Colours.Android.Resource.Color.hollyGreenColor = global::AndroidSample.Resource.Color.hollyGreenColor;
			global::Colours.Android.Resource.Color.holo_blue_bright = global::AndroidSample.Resource.Color.holo_blue_bright;
			global::Colours.Android.Resource.Color.holo_blue_dark = global::AndroidSample.Resource.Color.holo_blue_dark;
			global::Colours.Android.Resource.Color.holo_blue_light = global::AndroidSample.Resource.Color.holo_blue_light;
			global::Colours.Android.Resource.Color.holo_green_dark = global::AndroidSample.Resource.Color.holo_green_dark;
			global::Colours.Android.Resource.Color.holo_green_light = global::AndroidSample.Resource.Color.holo_green_light;
			global::Colours.Android.Resource.Color.holo_orange_dark = global::AndroidSample.Resource.Color.holo_orange_dark;
			global::Colours.Android.Resource.Color.holo_orange_light = global::AndroidSample.Resource.Color.holo_orange_light;
			global::Colours.Android.Resource.Color.holo_purple = global::AndroidSample.Resource.Color.holo_purple;
			global::Colours.Android.Resource.Color.holo_red_dark = global::AndroidSample.Resource.Color.holo_red_dark;
			global::Colours.Android.Resource.Color.holo_red_light = global::AndroidSample.Resource.Color.holo_red_light;
			global::Colours.Android.Resource.Color.honeydewColor = global::AndroidSample.Resource.Color.honeydewColor;
			global::Colours.Android.Resource.Color.icebergColor = global::AndroidSample.Resource.Color.icebergColor;
			global::Colours.Android.Resource.Color.indianRedColor = global::AndroidSample.Resource.Color.indianRedColor;
			global::Colours.Android.Resource.Color.indigoColor = global::AndroidSample.Resource.Color.indigoColor;
			global::Colours.Android.Resource.Color.infoBlueColor = global::AndroidSample.Resource.Color.infoBlueColor;
			global::Colours.Android.Resource.Color.ivoryColor = global::AndroidSample.Resource.Color.ivoryColor;
			global::Colours.Android.Resource.Color.lavenderColor = global::AndroidSample.Resource.Color.lavenderColor;
			global::Colours.Android.Resource.Color.lightCreamColor = global::AndroidSample.Resource.Color.lightCreamColor;
			global::Colours.Android.Resource.Color.limeColor = global::AndroidSample.Resource.Color.limeColor;
			global::Colours.Android.Resource.Color.linenColor = global::AndroidSample.Resource.Color.linenColor;
			global::Colours.Android.Resource.Color.mandarinColor = global::AndroidSample.Resource.Color.mandarinColor;
			global::Colours.Android.Resource.Color.maroonColor = global::AndroidSample.Resource.Color.maroonColor;
			global::Colours.Android.Resource.Color.midnightBlueColor = global::AndroidSample.Resource.Color.midnightBlueColor;
			global::Colours.Android.Resource.Color.moneyGreenColor = global::AndroidSample.Resource.Color.moneyGreenColor;
			global::Colours.Android.Resource.Color.mudColor = global::AndroidSample.Resource.Color.mudColor;
			global::Colours.Android.Resource.Color.mustardColor = global::AndroidSample.Resource.Color.mustardColor;
			global::Colours.Android.Resource.Color.oldLaceColor = global::AndroidSample.Resource.Color.oldLaceColor;
			global::Colours.Android.Resource.Color.oliveColor = global::AndroidSample.Resource.Color.oliveColor;
			global::Colours.Android.Resource.Color.oliveDrabColor = global::AndroidSample.Resource.Color.oliveDrabColor;
			global::Colours.Android.Resource.Color.orchidColor = global::AndroidSample.Resource.Color.orchidColor;
			global::Colours.Android.Resource.Color.paleGreenColor = global::AndroidSample.Resource.Color.paleGreenColor;
			global::Colours.Android.Resource.Color.palePurpleColor = global::AndroidSample.Resource.Color.palePurpleColor;
			global::Colours.Android.Resource.Color.paleRoseColor = global::AndroidSample.Resource.Color.paleRoseColor;
			global::Colours.Android.Resource.Color.pastelBlueColor = global::AndroidSample.Resource.Color.pastelBlueColor;
			global::Colours.Android.Resource.Color.pastelGreenColor = global::AndroidSample.Resource.Color.pastelGreenColor;
			global::Colours.Android.Resource.Color.pastelOrangeColor = global::AndroidSample.Resource.Color.pastelOrangeColor;
			global::Colours.Android.Resource.Color.pastelPurpleColor = global::AndroidSample.Resource.Color.pastelPurpleColor;
			global::Colours.Android.Resource.Color.peachColor = global::AndroidSample.Resource.Color.peachColor;
			global::Colours.Android.Resource.Color.periwinkleColor = global::AndroidSample.Resource.Color.periwinkleColor;
			global::Colours.Android.Resource.Color.pinkColor = global::AndroidSample.Resource.Color.pinkColor;
			global::Colours.Android.Resource.Color.pinkLipstickColor = global::AndroidSample.Resource.Color.pinkLipstickColor;
			global::Colours.Android.Resource.Color.plumColor = global::AndroidSample.Resource.Color.plumColor;
			global::Colours.Android.Resource.Color.raspberryColor = global::AndroidSample.Resource.Color.raspberryColor;
			global::Colours.Android.Resource.Color.robinEggColor = global::AndroidSample.Resource.Color.robinEggColor;
			global::Colours.Android.Resource.Color.salmonColor = global::AndroidSample.Resource.Color.salmonColor;
			global::Colours.Android.Resource.Color.sandColor = global::AndroidSample.Resource.Color.sandColor;
			global::Colours.Android.Resource.Color.seafoamColor = global::AndroidSample.Resource.Color.seafoamColor;
			global::Colours.Android.Resource.Color.seashellColor = global::AndroidSample.Resource.Color.seashellColor;
			global::Colours.Android.Resource.Color.siennaColor = global::AndroidSample.Resource.Color.siennaColor;
			global::Colours.Android.Resource.Color.skyBlueColor = global::AndroidSample.Resource.Color.skyBlueColor;
			global::Colours.Android.Resource.Color.snowColor = global::AndroidSample.Resource.Color.snowColor;
			global::Colours.Android.Resource.Color.steelBlueColor = global::AndroidSample.Resource.Color.steelBlueColor;
			global::Colours.Android.Resource.Color.strawberryColor = global::AndroidSample.Resource.Color.strawberryColor;
			global::Colours.Android.Resource.Color.successColor = global::AndroidSample.Resource.Color.successColor;
			global::Colours.Android.Resource.Color.tealColor = global::AndroidSample.Resource.Color.tealColor;
			global::Colours.Android.Resource.Color.tomatoColor = global::AndroidSample.Resource.Color.tomatoColor;
			global::Colours.Android.Resource.Color.turquoiseColor = global::AndroidSample.Resource.Color.turquoiseColor;
			global::Colours.Android.Resource.Color.violetColor = global::AndroidSample.Resource.Color.violetColor;
			global::Colours.Android.Resource.Color.warmGrayColor = global::AndroidSample.Resource.Color.warmGrayColor;
			global::Colours.Android.Resource.Color.warningColor = global::AndroidSample.Resource.Color.warningColor;
			global::Colours.Android.Resource.Color.watermelonColor = global::AndroidSample.Resource.Color.watermelonColor;
			global::Colours.Android.Resource.Color.waveColor = global::AndroidSample.Resource.Color.waveColor;
			global::Colours.Android.Resource.Color.wheatColor = global::AndroidSample.Resource.Color.wheatColor;
			global::Colours.Android.Resource.Color.white = global::AndroidSample.Resource.Color.white;
			global::Colours.Android.Resource.Color.yellowGreenColor = global::AndroidSample.Resource.Color.yellowGreenColor;
			global::Colours.Android.Resource.String.library_name = global::AndroidSample.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f04005f
			public const int almondColor = 2130968671;
			
			// aapt resource value: 0x7f040005
			public const int antiqueWhiteColor = 2130968581;
			
			// aapt resource value: 0x7f04001d
			public const int babyBlueColor = 2130968605;
			
			// aapt resource value: 0x7f040065
			public const int background_dark = 2130968677;
			
			// aapt resource value: 0x7f04006a
			public const int background_holo_dark = 2130968682;
			
			// aapt resource value: 0x7f04006b
			public const int background_holo_light = 2130968683;
			
			// aapt resource value: 0x7f040066
			public const int background_light = 2130968678;
			
			// aapt resource value: 0x7f04004c
			public const int bananaColor = 2130968652;
			
			// aapt resource value: 0x7f040053
			public const int beigeColor = 2130968659;
			
			// aapt resource value: 0x7f04000f
			public const int black = 2130968591;
			
			// aapt resource value: 0x7f04000c
			public const int black25PercentColor = 2130968588;
			
			// aapt resource value: 0x7f04000d
			public const int black50PercentColor = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int black75PercentColor = 2130968590;
			
			// aapt resource value: 0x7f04001b
			public const int blueberryColor = 2130968603;
			
			// aapt resource value: 0x7f040031
			public const int brickRedColor = 2130968625;
			
			// aapt resource value: 0x7f040067
			public const int bright_foreground_dark = 2130968679;
			
			// aapt resource value: 0x7f040069
			public const int bright_foreground_dark_disabled = 2130968681;
			
			// aapt resource value: 0x7f04006e
			public const int bright_foreground_disabled_holo_dark = 2130968686;
			
			// aapt resource value: 0x7f04006f
			public const int bright_foreground_disabled_holo_light = 2130968687;
			
			// aapt resource value: 0x7f04006c
			public const int bright_foreground_holo_dark = 2130968684;
			
			// aapt resource value: 0x7f04006d
			public const int bright_foreground_holo_light = 2130968685;
			
			// aapt resource value: 0x7f040068
			public const int bright_foreground_light = 2130968680;
			
			// aapt resource value: 0x7f040055
			public const int burntOrangeColor = 2130968661;
			
			// aapt resource value: 0x7f04005b
			public const int burntSiennaColor = 2130968667;
			
			// aapt resource value: 0x7f04004e
			public const int buttermilkColor = 2130968654;
			
			// aapt resource value: 0x7f040027
			public const int cactusGreenColor = 2130968615;
			
			// aapt resource value: 0x7f040057
			public const int cantaloupeColor = 2130968663;
			
			// aapt resource value: 0x7f04002f
			public const int cardTableColor = 2130968623;
			
			// aapt resource value: 0x7f040058
			public const int carrotColor = 2130968664;
			
			// aapt resource value: 0x7f040012
			public const int charcoalColor = 2130968594;
			
			// aapt resource value: 0x7f040028
			public const int chartreuseColor = 2130968616;
			
			// aapt resource value: 0x7f04005a
			public const int chiliPowderColor = 2130968666;
			
			// aapt resource value: 0x7f04005c
			public const int chocolateColor = 2130968668;
			
			// aapt resource value: 0x7f04005e
			public const int cinnamonColor = 2130968670;
			
			// aapt resource value: 0x7f04005d
			public const int coffeeColor = 2130968669;
			
			// aapt resource value: 0x7f040011
			public const int coolGrayColor = 2130968593;
			
			// aapt resource value: 0x7f040041
			public const int coolPurpleColor = 2130968641;
			
			// aapt resource value: 0x7f040037
			public const int coralColor = 2130968631;
			
			// aapt resource value: 0x7f04001c
			public const int cornflowerColor = 2130968604;
			
			// aapt resource value: 0x7f040050
			public const int creamColor = 2130968656;
			
			// aapt resource value: 0x7f04003d
			public const int crimsonColor = 2130968637;
			
			// aapt resource value: 0x7f040003
			public const int dangerColor = 2130968579;
			
			// aapt resource value: 0x7f04001a
			public const int denimColor = 2130968602;
			
			// aapt resource value: 0x7f040071
			public const int dim_foreground_disabled_holo_dark = 2130968689;
			
			// aapt resource value: 0x7f040074
			public const int dim_foreground_disabled_holo_light = 2130968692;
			
			// aapt resource value: 0x7f040070
			public const int dim_foreground_holo_dark = 2130968688;
			
			// aapt resource value: 0x7f040073
			public const int dim_foreground_holo_light = 2130968691;
			
			// aapt resource value: 0x7f040064
			public const int dustColor = 2130968676;
			
			// aapt resource value: 0x7f040032
			public const int easterPinkColor = 2130968626;
			
			// aapt resource value: 0x7f04003e
			public const int eggplantColor = 2130968638;
			
			// aapt resource value: 0x7f040060
			public const int eggshellColor = 2130968672;
			
			// aapt resource value: 0x7f040022
			public const int emeraldColor = 2130968610;
			
			// aapt resource value: 0x7f04001f
			public const int fadedBlueColor = 2130968607;
			
			// aapt resource value: 0x7f040046
			public const int fuschiaColor = 2130968646;
			
			// aapt resource value: 0x7f040009
			public const int ghostWhiteColor = 2130968585;
			
			// aapt resource value: 0x7f04004f
			public const int goldColor = 2130968655;
			
			// aapt resource value: 0x7f04004a
			public const int goldenrodColor = 2130968650;
			
			// aapt resource value: 0x7f040047
			public const int grapeColor = 2130968647;
			
			// aapt resource value: 0x7f040033
			public const int grapefruitColor = 2130968627;
			
			// aapt resource value: 0x7f040023
			public const int grassColor = 2130968611;
			
			// aapt resource value: 0x7f040076
			public const int highlighted_text_holo_dark = 2130968694;
			
			// aapt resource value: 0x7f040077
			public const int highlighted_text_holo_light = 2130968695;
			
			// aapt resource value: 0x7f040072
			public const int hint_foreground_holo_dark = 2130968690;
			
			// aapt resource value: 0x7f040075
			public const int hint_foreground_holo_light = 2130968693;
			
			// aapt resource value: 0x7f040029
			public const int hollyGreenColor = 2130968617;
			
			// aapt resource value: 0x7f040081
			public const int holo_blue_bright = 2130968705;
			
			// aapt resource value: 0x7f04007b
			public const int holo_blue_dark = 2130968699;
			
			// aapt resource value: 0x7f040078
			public const int holo_blue_light = 2130968696;
			
			// aapt resource value: 0x7f04007c
			public const int holo_green_dark = 2130968700;
			
			// aapt resource value: 0x7f040079
			public const int holo_green_light = 2130968697;
			
			// aapt resource value: 0x7f040080
			public const int holo_orange_dark = 2130968704;
			
			// aapt resource value: 0x7f04007f
			public const int holo_orange_light = 2130968703;
			
			// aapt resource value: 0x7f04007e
			public const int holo_purple = 2130968702;
			
			// aapt resource value: 0x7f04007d
			public const int holo_red_dark = 2130968701;
			
			// aapt resource value: 0x7f04007a
			public const int holo_red_light = 2130968698;
			
			// aapt resource value: 0x7f04002d
			public const int honeydewColor = 2130968621;
			
			// aapt resource value: 0x7f040020
			public const int icebergColor = 2130968608;
			
			// aapt resource value: 0x7f040035
			public const int indianRedColor = 2130968629;
			
			// aapt resource value: 0x7f040019
			public const int indigoColor = 2130968601;
			
			// aapt resource value: 0x7f040000
			public const int infoBlueColor = 2130968576;
			
			// aapt resource value: 0x7f040007
			public const int ivoryColor = 2130968583;
			
			// aapt resource value: 0x7f040044
			public const int lavenderColor = 2130968644;
			
			// aapt resource value: 0x7f040051
			public const int lightCreamColor = 2130968657;
			
			// aapt resource value: 0x7f04002e
			public const int limeColor = 2130968622;
			
			// aapt resource value: 0x7f04000b
			public const int linenColor = 2130968587;
			
			// aapt resource value: 0x7f040059
			public const int mandarinColor = 2130968665;
			
			// aapt resource value: 0x7f040038
			public const int maroonColor = 2130968632;
			
			// aapt resource value: 0x7f04001e
			public const int midnightBlueColor = 2130968606;
			
			// aapt resource value: 0x7f04002c
			public const int moneyGreenColor = 2130968620;
			
			// aapt resource value: 0x7f040062
			public const int mudColor = 2130968674;
			
			// aapt resource value: 0x7f04004d
			public const int mustardColor = 2130968653;
			
			// aapt resource value: 0x7f040006
			public const int oldLaceColor = 2130968582;
			
			// aapt resource value: 0x7f04002a
			public const int oliveColor = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int oliveDrabColor = 2130968619;
			
			// aapt resource value: 0x7f040049
			public const int orchidColor = 2130968649;
			
			// aapt resource value: 0x7f040026
			public const int paleGreenColor = 2130968614;
			
			// aapt resource value: 0x7f040040
			public const int palePurpleColor = 2130968640;
			
			// aapt resource value: 0x7f04003c
			public const int paleRoseColor = 2130968636;
			
			// aapt resource value: 0x7f040016
			public const int pastelBlueColor = 2130968598;
			
			// aapt resource value: 0x7f040024
			public const int pastelGreenColor = 2130968612;
			
			// aapt resource value: 0x7f040056
			public const int pastelOrangeColor = 2130968662;
			
			// aapt resource value: 0x7f04003f
			public const int pastelPurpleColor = 2130968639;
			
			// aapt resource value: 0x7f040054
			public const int peachColor = 2130968660;
			
			// aapt resource value: 0x7f040048
			public const int periwinkleColor = 2130968648;
			
			// aapt resource value: 0x7f040034
			public const int pinkColor = 2130968628;
			
			// aapt resource value: 0x7f04003b
			public const int pinkLipstickColor = 2130968635;
			
			// aapt resource value: 0x7f040043
			public const int plumColor = 2130968643;
			
			// aapt resource value: 0x7f040045
			public const int raspberryColor = 2130968645;
			
			// aapt resource value: 0x7f040015
			public const int robinEggColor = 2130968597;
			
			// aapt resource value: 0x7f040030
			public const int salmonColor = 2130968624;
			
			// aapt resource value: 0x7f040061
			public const int sandColor = 2130968673;
			
			// aapt resource value: 0x7f040025
			public const int seafoamColor = 2130968613;
			
			// aapt resource value: 0x7f040008
			public const int seashellColor = 2130968584;
			
			// aapt resource value: 0x7f040063
			public const int siennaColor = 2130968675;
			
			// aapt resource value: 0x7f040018
			public const int skyBlueColor = 2130968600;
			
			// aapt resource value: 0x7f04000a
			public const int snowColor = 2130968586;
			
			// aapt resource value: 0x7f040014
			public const int steelBlueColor = 2130968596;
			
			// aapt resource value: 0x7f040036
			public const int strawberryColor = 2130968630;
			
			// aapt resource value: 0x7f040001
			public const int successColor = 2130968577;
			
			// aapt resource value: 0x7f040013
			public const int tealColor = 2130968595;
			
			// aapt resource value: 0x7f04003a
			public const int tomatoColor = 2130968634;
			
			// aapt resource value: 0x7f040017
			public const int turquoiseColor = 2130968599;
			
			// aapt resource value: 0x7f040042
			public const int violetColor = 2130968642;
			
			// aapt resource value: 0x7f040010
			public const int warmGrayColor = 2130968592;
			
			// aapt resource value: 0x7f040002
			public const int warningColor = 2130968578;
			
			// aapt resource value: 0x7f040039
			public const int watermelonColor = 2130968633;
			
			// aapt resource value: 0x7f040021
			public const int waveColor = 2130968609;
			
			// aapt resource value: 0x7f040052
			public const int wheatColor = 2130968658;
			
			// aapt resource value: 0x7f040004
			public const int white = 2130968580;
			
			// aapt resource value: 0x7f04004b
			public const int yellowGreenColor = 2130968651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int border = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int myButton = 2131099648;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ColorPaletteResource = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050002
			public const int app_name = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int hello = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
